name: Say Hello

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"
